language: java
addons:
  sonarcloud:
    organization: revaturelabs
    token:
      secure: VqryoMtV3wQqxAMSqTJafueMslCssHIWO48ZWxASYIeMv0BlG82EM8m1S2LEHWeRcaIN2cS1OOgTxgtQDF/UQjGUQQG+OON4mrd6XU4aaB7rOVvQJVSLin4UmxsvV6lZj0sbuPEE1JgAIvrE5SSQrTISYuy6tAoks8FPCKQykUDYnCNwfALrP00OHFQbe4YkWJ8L+pVFKQsx8uiNuvYqxiCPUrF36KB4RMXP4GUu+Iyn5HgS1w4m44Rem0TtIUg9Nf6AvUtnU1e43fIPdAdRitYb2MZ5e7hJ9Y8OAN0HY6HecbhQWA0zUiyUAw4RhzUgba769X2OB4IxF07DLX17TQbpwaP8/70YiqdKbtgBkj3pXWWC5Z2XIkU9iCnJ6l3KnOJUD+ZPMqWCZRYRyxbBqJp4+GYD+ROldj3IRv33b5dxrhYUgO94qrYxUSZ6HNjuhZwcgdFB9m+RqPCCr06UoVVdIm2OhAgnFMFSnLzsf29FdVpl6puDnDkqG7puYOplt2ifP5zXQSInLbXILrAmpGY5E7ty9V9x6w2CJnJcHgGcu41eVzHt8d8Bo8qVFeyPTrbu6PbP16OAb3yu/M9L1sM7hv80ifizK+Urb8u9Hr4x8Z4S0HAf+KLe9M1KwnEmTxp3BRZqmN3GhmuPznIqcWFQ1oi+YxTaekDPBHFO/J0=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch=develop
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: bdjUCnpJqeIAf+2ZiZ614MuCDKPlEQuxBxFWhGvJhVMnPBi6cT5r1A+LdghWM0lBUNNYnn/ImL8tVywQHIrYif/DhBJ70L7KBl1c39SHV/Sh4U630r8R1zXPAlkA7ez3L6TgWKtiKBy3oYGmMi+Zl3Tb9NLkFNuy1fN4ATbmuAp7qgIyi9MQg6OCNFbUdPlv51lCM/Gfid60XQMpd0mm/H1oV5pSfiZEX7C/eVBAi8cy9oMUkgpbbWqW8aZ/HLwnTDJArUyCr+gw8nVnXDfWoV7GIKhkacn4usLaQqBSiQ2GR7UZvQf8Ev577einEKEMX0ECK8XW1DvnbrTAdC11xumFXE1wZCSTDobpfgWAYr162tkMEn4DyPD0CWLCv+t9NEEY/TKHzeDfcLXIbp7BoOP91z9Y4JTEFwKPHgrTK+sL3R5m75sFSTBmwCfWaQGypVWzDnwNWBpjP9RQFIOHAbCBpHZx0eBd7+hKi2Pbk+10ROShtoUjMTFuwVeNk4KAljSDwdw8LytPdvl7roLL03bSrlZAXSYLmNe0XDdRfQOtkd8/mleGqq0eZlKpygkxknINjYwY/mIRTRvSi+nfMFpz2+LHzGCCfHR03AhwVulAdaLfGEiR2/5T3Ic/zKVS8QL4MCSTyirJFS/74tfglDYUqgMA1ItiBPdKDltVbvc=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-batch-service
    branch: develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
