language: java
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: bdjUCnpJqeIAf+2ZiZ614MuCDKPlEQuxBxFWhGvJhVMnPBi6cT5r1A+LdghWM0lBUNNYnn/ImL8tVywQHIrYif/DhBJ70L7KBl1c39SHV/Sh4U630r8R1zXPAlkA7ez3L6TgWKtiKBy3oYGmMi+Zl3Tb9NLkFNuy1fN4ATbmuAp7qgIyi9MQg6OCNFbUdPlv51lCM/Gfid60XQMpd0mm/H1oV5pSfiZEX7C/eVBAi8cy9oMUkgpbbWqW8aZ/HLwnTDJArUyCr+gw8nVnXDfWoV7GIKhkacn4usLaQqBSiQ2GR7UZvQf8Ev577einEKEMX0ECK8XW1DvnbrTAdC11xumFXE1wZCSTDobpfgWAYr162tkMEn4DyPD0CWLCv+t9NEEY/TKHzeDfcLXIbp7BoOP91z9Y4JTEFwKPHgrTK+sL3R5m75sFSTBmwCfWaQGypVWzDnwNWBpjP9RQFIOHAbCBpHZx0eBd7+hKi2Pbk+10ROShtoUjMTFuwVeNk4KAljSDwdw8LytPdvl7roLL03bSrlZAXSYLmNe0XDdRfQOtkd8/mleGqq0eZlKpygkxknINjYwY/mIRTRvSi+nfMFpz2+LHzGCCfHR03AhwVulAdaLfGEiR2/5T3Ic/zKVS8QL4MCSTyirJFS/74tfglDYUqgMA1ItiBPdKDltVbvc=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-batch-service
    branch: develop
