language: java
addons:
  sonarcloud:
    organization: revaturelabs
    token:
      secure: RI3vBo9mccj0KS8qQ9CdZujW/soMGXFUspvZoxntoLm5Ggp2fuIItv5VhXSyJ8vXEQqfrn60Xv77ND1tBvz95WRFzHfHt93YHClppxIr2RogcqXCdh4bzJDDPhnoI080cTVG61LJg6+QCAG58uu6yN56cKK9YUG1BdmHqQtXrkO/OIuwc/d2AP6wsjH1MIlZGeDU5Y46zJDWQYMSEEDOh//UCBSMkfiLz9noYuHcUUWzFMjeZ/J6lN7M1oCyzlmkgs671KPZ0kz4x+Z1cJ0BFsgcFmGBc6uqP5gWH0AepXiU6r4FkEAj0Lh6zjVZ68JXpidePnb253hC0nZMvQVb/M7Wqnx1jt8X3ryU3A0wcpRvr4OK94FIHsSYXgGCDhpv4RhOE1gYM04XOQjaaa28VrqPxgM8FolfcBrWh0bc1WoOI7dC6XgPMqUwCg5zjnbd9R/iVaNMDMxbmH4FcXJREtqZndjWBiaqyaXsTJ6tsnqW+YSECuwNKuL7/DcsQhP5tN+9QzE50jhUjuDygzQT8CrPh6HCpf7DwwCuUEwGSwRoA39f35hNtpAHpO1qdZ26be8zVHOixTjop8CT2ekSLNxL+x1T67NCefsNa5EetYU9IR3rVtP8sRoDpjLbMZflgBD4WI3dOgfr7ctv4qce7RMejcVaDC2UyNA23vBpnYI=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: bdjUCnpJqeIAf+2ZiZ614MuCDKPlEQuxBxFWhGvJhVMnPBi6cT5r1A+LdghWM0lBUNNYnn/ImL8tVywQHIrYif/DhBJ70L7KBl1c39SHV/Sh4U630r8R1zXPAlkA7ez3L6TgWKtiKBy3oYGmMi+Zl3Tb9NLkFNuy1fN4ATbmuAp7qgIyi9MQg6OCNFbUdPlv51lCM/Gfid60XQMpd0mm/H1oV5pSfiZEX7C/eVBAi8cy9oMUkgpbbWqW8aZ/HLwnTDJArUyCr+gw8nVnXDfWoV7GIKhkacn4usLaQqBSiQ2GR7UZvQf8Ev577einEKEMX0ECK8XW1DvnbrTAdC11xumFXE1wZCSTDobpfgWAYr162tkMEn4DyPD0CWLCv+t9NEEY/TKHzeDfcLXIbp7BoOP91z9Y4JTEFwKPHgrTK+sL3R5m75sFSTBmwCfWaQGypVWzDnwNWBpjP9RQFIOHAbCBpHZx0eBd7+hKi2Pbk+10ROShtoUjMTFuwVeNk4KAljSDwdw8LytPdvl7roLL03bSrlZAXSYLmNe0XDdRfQOtkd8/mleGqq0eZlKpygkxknINjYwY/mIRTRvSi+nfMFpz2+LHzGCCfHR03AhwVulAdaLfGEiR2/5T3Ic/zKVS8QL4MCSTyirJFS/74tfglDYUqgMA1ItiBPdKDltVbvc=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-batch-service
    branch: develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
