language: java
addons:
  sonarcloud:
    organization: revaturelabs
    token:
      secure: mHoicV/e33tqt+Oc826/cmOwgdnetqb3PbiF6xneHyFz9ZBEsJ//fDp5UzXJFbmJ3J2jbXAhkb/Y1MsusaZX9CLoVssb1I3lF0g13pjb8cAMP0pl+E4Lq2LKyWAJ19bkshgZdHf60OA20bMHgeRWlez2CCvtwpSen5DVJhrsJaiXdTkl8DNMyftA0EFPapoc54pSGukeiOE6idO9ynEMUeGqD1mpjLWcGHPW79o1JJFmW9wX7jKwFoY6qDWC5zCsSkUGDPYeGYc2AZTh67I3/UTw/w+5xa5XGMq8D1UiMPcBOyOUNvUJhEWbacR0Vz2Zf63xMgSZIxSDpv1yH9EDYVNcLPgBB8cIXiMnXnCYajrxcjuQxXCYKY8RaW0QT2tCqb4mzOj7sBhz6lgEbehw6VRkhfYz+V+XvEt46wNHCWoBWonmUEn0Esbm9dprq4vcjoDYdBvItOXn343TZnNsFPhIiNY2rTHmf0xE6tLQt8O9UdiDX4OcY+ly8GlXCsj/frLFTVzej0F+5FCj5cNMdD96mBFkpsXlvY2eQN4jxrSQ2IgUIArV0yU0YNWJQoXUfHdRtEwCPDSjFkL8Rs57exwZv3SPrxjCAj9ZggXUddTkX4ShKTJ/dkobzt/N6ecBLmkdTAAFrtht18pe8nLAxtRV4DKzx7Zjwz2Go9GJxOA=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: bdjUCnpJqeIAf+2ZiZ614MuCDKPlEQuxBxFWhGvJhVMnPBi6cT5r1A+LdghWM0lBUNNYnn/ImL8tVywQHIrYif/DhBJ70L7KBl1c39SHV/Sh4U630r8R1zXPAlkA7ez3L6TgWKtiKBy3oYGmMi+Zl3Tb9NLkFNuy1fN4ATbmuAp7qgIyi9MQg6OCNFbUdPlv51lCM/Gfid60XQMpd0mm/H1oV5pSfiZEX7C/eVBAi8cy9oMUkgpbbWqW8aZ/HLwnTDJArUyCr+gw8nVnXDfWoV7GIKhkacn4usLaQqBSiQ2GR7UZvQf8Ev577einEKEMX0ECK8XW1DvnbrTAdC11xumFXE1wZCSTDobpfgWAYr162tkMEn4DyPD0CWLCv+t9NEEY/TKHzeDfcLXIbp7BoOP91z9Y4JTEFwKPHgrTK+sL3R5m75sFSTBmwCfWaQGypVWzDnwNWBpjP9RQFIOHAbCBpHZx0eBd7+hKi2Pbk+10ROShtoUjMTFuwVeNk4KAljSDwdw8LytPdvl7roLL03bSrlZAXSYLmNe0XDdRfQOtkd8/mleGqq0eZlKpygkxknINjYwY/mIRTRvSi+nfMFpz2+LHzGCCfHR03AhwVulAdaLfGEiR2/5T3Ic/zKVS8QL4MCSTyirJFS/74tfglDYUqgMA1ItiBPdKDltVbvc=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-batch-service
    branch: develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
