spring:
  profiles:
    active: production

---

spring:
  profiles: production
  application:
    name: batch
  cloud:
    services:
      registrationMethod: direct
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    register-with-eureka: true
    leaseRenewalIntervalInSeconds: 10
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

security:
  basic:
    enabled: false

server:
  servlet:
    contextPath: /v0

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  rabbitmq:
    listener:
      simple:
        auto-startup: false
eureka:
  client:
    enabled: false
security:
  basic:
    enabled: false

