spring:
  profiles:
    active: batchservice

---

spring:
  application:
    name: batch
  cloud:
    services:
      registrationMethod: direct
  profiles: batchservice
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    register-with-eureka: true
    leaseRenewalIntervalInSeconds: 10
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

security:
  basic:
    enabled: false

server:
  servlet:
    contextPath: /v0

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
