--------------------------------------------------------
--    DDL for BATCH_LOCATION Table 
--------------------------------------------------------
DROP TABLE IF EXISTS BATCH_LOCATION;
    
CREATE TABLE BATCH_LOCATION (
	BATCH_LOCATION_ID INT(10) PRIMARY KEY,
	LOCATION_ID INT(10),
	BUILDING_ID INT(10),
	ROOM_ID INT(10)
    ); 
    
--------------------------------------------------------
--    DDL for BATCH_STATUS LOOKUP Table 
--------------------------------------------------------

DROP TABLE IF EXISTS BATCH_STATUS_LOOKUP;

CREATE TABLE BATCH_STATUS_LOOKUP(
	BATCH_STATUS_ID INT(10) PRIMARY KEY,
	BS_NAME VARCHAR(255) NOT NULL
);
    
--------------------------------------------------------
--    DDL for BATCH Table 
--------------------------------------------------------    
DROP TABLE IF EXISTS BATCH; 

CREATE TABLE BATCH(
	BATCH_ID INT(10) PRIMARY KEY,
	RESOURCE_ID INT(10),
	TRAINING_NAME VARCHAR(255) NOT NULL,
	TRAINER_ID INT(10) NOT NULL,
	CO_TRAINER_ID INT(10),
	SKILL_TYPE VARCHAR(255) NOT NULL,
	TRAINING_TYPE VARCHAR(255) NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	LOCATION VARCHAR(255) NOT NULL,
	BATCH_LOCATION INT(10) REFERENCES BATCH_LOCATION(BATCH_LOCATION_ID),
	ADDRESS_ID INT(10),
	GOOD_GRADE_THRESHOLD INT(5) NOT NULL CHECK(GOOD_GRADE_THRESHOLD>1),
	BORDERLINE_GRADE_THRESHOLD INT(5) NOT NULL CHECK(BORDERLINE_GRADE_THRESHOLD>1),
	NUMBER_OF_WEEKS INT(10) NOT NULL,
	GRADED_WEEKS INT(10) NOT NULL,
	CURRICULUM INT(10),
	FOCUS INT(10),
	STATUS INT(10) REFERENCES BATCH_STATUS_LOOKUP(BATCH_STATUS_ID)

);




--------------------------------------------------------
--    DDL for BATCH_SKILL_JT Table
--------------------------------------------------------

DROP TABLE IF EXISTS BATCH_SKILL_JT;

CREATE TABLE BATCH_SKILL_JT(
	BATCH_ID INT(10) PRIMARY KEY,
	SKILL_ID INT(10)
);


--------------------------------------------------------
--  DDL for Sequence BATCH_ID_SEQUENCE
--------------------------------------------------------
DROP SEQUENCE IF EXISTS BATCH_ID_SEQUENCE;   
CREATE SEQUENCE  IF NOT EXISTS  BATCH_ID_SEQUENCE  MINVALUE 2210  INCREMENT BY 1 START WITH 2210;

--------------------------------------------------------
--  DDL for Sequence BATCH_STATUS_SEQUENCE
--------------------------------------------------------
DROP SEQUENCE IF EXISTS BATCH_STATUS_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS BATCH_STATUS_SEQUENCE MINVALUE 1 INCREMENT BY 1 START WITH 1;

--------------------------------------------------------
--  DDL for Sequence BATCH_LOCATION_SEQUENCE
--------------------------------------------------------
DROP SEQUENCE IF EXISTS BATCH_LOCATION_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS BATCH_LOCATION_SEQUENCE MINVALUE 1 INCREMENT BY 1 START WITH 1;



--------------------------------------------------------
--  DML for Database initialization
--------------------------------------------------------
INSERT into BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) values (2200,70,(SYSDATE+14),80,'Tech Incubator at Queens College, 65-30 Kissena Blvd, CEP Hall 2, Queens, NY 11367','J2EE',(SYSDATE-28),'1611 Nov14 Java (AP)','University',9,null,1,1,7);
INSERT into BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) values (2201,70,(SYSDATE+28),80,'Tech Incubator at Queens College, 65-30 Kissena Blvd, CEP Hall 2, Queens, NY 11367','J2EE',(SYSDATE-7),'1702 Feb13 Java (AP)','University',7,null,1,1,7);
INSERT into BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) values (2050,70,(SYSDATE-48),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',             (SYSDATE-72),'1602 Feb08 Java','Revature',8,null,1,2,7);
INSERT into BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) values (2100,70,(SYSDATE-14),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',             (SYSDATE-35),'1604 Apr25 Java','Revature',7,null,1,2,7);
INSERT into BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) values (2150,70,(SYSDATE+64),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',             (SYSDATE+28),'1607 Jul11 Java','Revature',7,null,1,2,7);
INSERT into BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) values (2003,70,'2016-01-01',80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',             '2016-01-01','1509 Sept11 Java (delete)','Revature',1,null,1,2,7);
INSERT INTO BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) VALUES (3000,70,(SYSDATE+10),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',(SYSDATE-10),'1800 Oct16 Java','Revature',7,null,20,2,7);
INSERT INTO BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) VALUES (3001,70,(SYSDATE+10),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',(SYSDATE-10),'1801 Oct16 Java','Revature',7,null,2,2,7);
INSERT INTO BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) VALUES (3002,70,(SYSDATE+10),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',(SYSDATE-10),'1802 Oct16 Java','Revature',7,null,21,2,7);
INSERT INTO BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) VALUES (3003,70,(SYSDATE+10),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',(SYSDATE-10),'1803 Oct16 Java','Revature',7,null,22,2,7);
INSERT INTO BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) VALUES (3004,70,(SYSDATE+10),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',(SYSDATE-10),'1804 OCT26 Java','Revature',7,null,23,2,7);
INSERT INTO BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) VALUES (3005,70,(SYSDATE-10),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',(SYSDATE-20),'1805 OCT26 Java','Revature',7,null,24,2,7);
INSERT INTO BATCH (BATCH_ID,BORDERLINE_GRADE_THRESHOLD,END_DATE,GOOD_GRADE_THRESHOLD,LOCATION,SKILL_TYPE,START_DATE,TRAINING_NAME,TRAINING_TYPE,NUMBER_OF_WEEKS,CO_TRAINER_ID,TRAINER_ID,ADDRESS_ID,GRADED_WEEKS) VALUES (3006,70,(SYSDATE+10),80,'Revature LLC, 11730 Plaza America Drive, 2nd Floor | Reston, VA 20190','J2EE',(SYSDATE-10),'1806 NOV08 Java','Revature',7,null,25,2,7);
COMMIT;